//TimesFive.groovy (Cthulhu)

String str = '''

DUNCAN JAREDIDCH, age 35, Wild Card

Jaredhich wears two .45 automatic pistols, one in a shoulder
holster (with 6 shots left) and one at his hip (with 2 shots). A
large knife is scabbarded at his belt. He also carries an Elder Sign.
Serves the Mi-Go.

STR 12(70) CON 11(70) SIZ 14(75) INT 12 POW 10(55)
DEX 13 APP 9(60) EDU 13 SAN 0 HP 13(75)
Damage Bonus: +1D4.
Weapons: .45 automatic pistol (x2) 65%, damage 1D10+2
Large Knife 55%, damage 1D4+2 1D4
Brawl 70%, damage 1D3+1D4
Skills: Cthulhu Mythos 15%, Dodge 40%, Drive Automobile
60%, Hide 25%, Jump 55%, Listen 35%, Mechanical Repair 45%,
Occult 25%, Pilot Airplane 55%, Sneak 50%, Spot Hidden 40%.
Languages: English 65%, Russian 25%.

VICTOR MONTAIN, age 58, Family Friend

STR 12 CON 14 SIZ 15 INT 15 POW 12
DEX 8 APP 13 EDU 15 SAN 40 HP 15
Damage Bonus: +1D4.
Skills: Bargain 90%, Credit Rating 70%, Persuade 50%
Languages: English 75%, French 95%, Quechua 60%

MARIA MONTAIN, age 33, Victor's Wife

Victor's wife Maria is a full-blooded Indian, born and raised in Huancucho. She does most of the work around the trading post while Victor orders her around in Quechua. She speaks no English, but if the party manages to communicate with her, she will be able to provide the most accurate version of the "Ghost" legend to be found.

STR 13 CON 14 SIZ 8 INT 9 POW 10
DEX 11 APP 9 SAN 50 EDU 4 HP 11

Damage Bonus: +0.
Skills: Occult (local) 60%.
Languages: French 15%, Quechua 40%, Spanish 15%.

SANCHO, age 28, Hard-working Guide (Maria's younger brother)

STR 12 CON 12 SIZ 9 INT 14 POW 11
DEX 14 APP 15 EDU 8 SAN 55 HP 11
Damage Bonus: +0
Skills: Bargain 55%, Climb 90%, Jump 80%, Ride Llama 85%.
Languages: English 25%, French 20%, Quechua 55%, Spanish 45%

DR. LAWRENCE RICHARDS, age 33, Camp Physician

STR 10 CON 11 SIZ 10 INT 17 POW 14
DEX 12 APP 14 EDU 21 SAN 70 HP 11

Damage Bonus: +0
Skills: Anthropology 25%, Archaeology 25%, Chemistry 20%,
First Aid 90%, Medicine 85%, Pharmacy 20%.
Languages: English 95%, Latin 45%.

HUARI INDIANS (all same)

STR 12 CON 14 SIZ 12 INT 11 POW 10
DEX 12 APP 12 EDU 2 HP 12

Damage Bonus: +1D4.
Weapons: .30-06 Bolt-action Rifle 40%, damage 2D6+4
Knife 60%, damage 1D6+1D4
FistlPunch 40%, damage 1D3+1D4
Skills: Hide 60%, Sneak 40%.
Languages: Quechua 50%.
Spells: One Huari is a priest of Yig and knows Bind Sacred Snake of Yig, Contact Yig, and Summon Sacred Snake of Yig.

NGANSA, age 100+ "The Ghost That Walks"

STR 14 CON 18 SIZ 12 INT 18 POW 20
DEX 18 APP 16 EDU 20 SAN 69 HP 15

Damage Bonus: + 1D4.
Skills: Cthulhu Mytho 20%, Hide 100%, Listen 90%, Sneak 100%, Spot Hidden 80%, Track 95%.
Languages: English 15%, French 25%, Montagnais 100%.
Armor: The paste that Ngansa has smeared on his body is a special mixture that he has prepared himself. It serves to repel mi-go, who are allergic to it. The material is toxic to the mi-go's alien biology and induce an extremely painful burning sensation on contact. The paste will also provide some protection from the intense heat generated by Cthugha.
Spells: Call Cthugha, Call Ithaqua.

JUAN GOYO, age 37, Peruvian Revolutionary and possible ally or enemy

STR 15 CON 17 SIZ 16 INT 15 POW 14
DEX 16 APP 16 EDU 10 SAN 55 HP 17
Damage Bonus: +1D4.
Weapons: .30-06 Bolt-action Rifle 90%, damage 2D6+4
.45 Revolver 85%, damage 1D10+2
Knife 90%, damage 2D4+2
Skills: Fast Talk 45%, First Aid 75%, Hide 75%, Listen 65%, Navigate 60%, Persuade 80%, Pick Pocket 75%, Psychology 75%, Sneak 75%, Track 30%.
Languages: English 35%, Quechua 50%, Spanish 65%.

AVERAGE REBEL (all same)

STR 15 CON 14 SIZ 14 INT 10 POW 10
DEX 14 APP 10 EDU 3 SAN 45 HP 14

Damage Bonus: +1D4
Weapons: .30-06 Bolt-action Rifle 70%, damage 2D6+4
.45 Revolver 80%, damage 1D10+2
Knife 75%, damage 2D4+2
Skills: Hide 55%, Pick Pocket 55%, Sneak 65%.

JONATHAN HARRIS, age 39, Mining Engineer

STR 14 CON 16 SIZ 15 INT 16 POW 11
DEX 12 APP 13 EDU 18 SAN 0 HP 16
Damage Bonus: +1D4.
Weapons: .45 Revolver 50%, damage ID10+2
Skills: Chemistry 25%, Cthulhu Mythos 50%, Geology 95%
Languages: English 90%, Spanish 25%.
Spells: Contact Mi-go.

MELVIN PEALE, age 42, Mine Security Chief

STR 15 CON 16 SIZ 10 INT 15 POW 12
DEX 16 APP 9 EDU 14 SAN 25 HP 13
Damage Bonus: +1D4.
Weapons: .45 Revolver 65%, damage 1D10+2
.30-06 Bolt-action Rifle 80%, damage 2D6+4 damage
Skills: Fast Talk 30%, Hide 75%, Listen 60%, Persuade 65%,
Psychology 25%, Sneak 80%, Spot Hidden 75%, Track 60%.

NWI SECURITY GUARDS (all same)

STR 15 CON 16 SIZ 14 INT 10 POW 10
DEX 15 APP 9 EDU 8 SAN 35 HP 15
Damage Bonus: +1D4.
Weapons: .30-06 Bolt-action Rifle 85%, damage 2D6+4
.45 Revolver 75%, damage 1D10+2
Knife 60%, damage 2D4+2
Skills: Hide 50%, Sneak 65%, Spot Hidden 65%, Track 75%.

MI-GO MINERS (eight, all same) - 0/1D6 SAN to see
STR 10 CON 10 SIZ 10 INT 13 POW 13
DEX 14 HP 10
Move 7/9 Flying
Weapons: Fighting 30%, damage 1D6
  Seize (mnvr) fly and drop from a height (or lungs burst)
Cryoray* (only 2 have), damage 2D8
Dodge: 35%
Armor: none, but impaling weapons (including bullets) do minimum damage
One Mi-go knows the spell Implant Fear (costs victim 0/1D6 SAN and they are compelled to run, no POW vs POW roll)

*An odd-shaped piece of gray metal that looks like a cluster of metal bubbles and glass pines. It shoots a visible beam of cold that cause 2D8 points of damage at a base range of twenty yards. The beam is slow, and a successful Dodge roll will allow someone to avoid it if he does nothing else that round. This is a small weapon designed for sentries and holds only twelve charges. An untrained user will have a base chance of 10% to use it succesfully. 

MI-GO SURGEONS (four, all same) - 0/1D6 SAN to see (grant bonus die if miners already seen)
STR 10 CON 10 SIZ 10 INT 13 POW 13
DEX 14 HP 10
Move 7/9 Flying
Weapons: Fighting 30%, damage 1D6
  Laser-knife 60% damage 2D6
Dodge: 35%
Armor: none, but impaling weapons (including bullets) do minimum damage

'''

/* ----------------------------------------------------------- */


str.eachLine() {
   line ->
   line = transformLine(line);
   println line
}


String transformLine(String line) {

   line = transform(line, "STR")
   line = transform(line, "CON")
   line = transform(line, "SIZ")
   line = transform(line, "POW")
   line = transform(line, "DEX")
   line = transform(line, "APP")               
   line = transform(line, "EDU")    
   line = transform(line, "INT")    
   return line
}

String transform(String line, String attr) {

   java.util.regex.Pattern p =
      java.util.regex.Pattern.compile("${attr}\\s([0-9]+)");

   java.util.regex.Matcher m = p.matcher(line)
   
   if (m.find()) {

      //println m.group(0);  //STR 12
      //println m.group(1);  //12
   
      Integer i = 5 * new Integer(m.group(1));
 
      //println line
      //println "$attr - Replaced with"      
   
      line = line.replace(m.group(0), "$attr " + i + "  ")
      
      //println line 
      //println ();
     
   }

   return line
}






